### PR TITLE
fix window onload event waiting in modern browsers

### PR DESCRIPTION
**Pull request by Chetter2**

### CODE REVIEW

**Comment by jrburke** [comment]
What is the motivation for this change? In general, I want to avoid browser user agent sniffing, as it is brittle, and I believe there some embedded IE cases where it could fail?

**Comment by Chetter2** [comment]
There is no need to wait until all sub-resources finish loading for domReady module, isn't it? 
In my case infrustructure waits for require('domReady!') and I am loosing seconds on initialization.

I found the way userAgent in embedded IE can be changed:
http://www.autoitscript.com/forum/topic/151454-how-to-fully-change-user-agent/
It looks like they shoot themself in the foot.
But there is still conditional compilation, if care about them.

**Comment by nikolas** [comment]
I agree that we shouldn't look at the user agent, but in any case domReady really needs to wait for `readyState === "interactive"` instead of `readyState === "loaded"`. This is causing a bug on something I'm working on, where a page is loading images from graphite that take 8-10 seconds to load. As a result, and without this change, the domReady plugin doesn't initialize my JS code until then, causing confusion for users.

**Comment by nikolas** [comment]
Although listening for `readyState === "interactive"` works for my cases, since no one who uses the sites I work on are using IE9, we should look at how jQuery is implementing their `.ready()` because it seems to work in all cases, and is very well tested.

They aren't waiting for `readyState === "interactive"` because of the IE9 bug:
https://github.com/jquery/jquery/blob/master/src/core/ready.js#L81
http://bugs.jquery.com/ticket/12282#comment:15

However, jQuery's `$.ready()` doesn't seem to unnecessarily delay for me on sites with large images, like `domReady` does. I think we need to come up with another fix for this -- one that definitely doesn't look at `window.navigator.userAgent`, and that doesn't listen for `readyState === "interactive"` either.

**Comment by Chetter2** [comment]
Here is synthetic test for jQuery's $.ready()
https://github.com/Chetter2/test-jquery-ready
It doesn't work properly if you loads it asyncronously (bundles file for example).
image

**Comment by jrburke** [comment]
@nikolas thanks for the pointers to the issue reported in jQuery. So with that, I am not comfortable merging this as-is, however, I am up for allowing a function to be passed in via module config to the domReady plugin, and it would delegate to that function if defined for detecting the DOM loaded case.

This would allow people that do not have concerns around user agent detection or the IE concern to provide a function that does the sort of check this function does. How does that sound?

**Comment by nikolas** [comment]
It might also be worth looking at dojo's domReady, since they are using this with their AMD loader: https://github.com/dojo/dojo/blob/master/domReady.js

**Pull request closed without merging**
